### ISSUE TITLE
Add option for aggregate value

### ISSUE THREAD

**Issue by kyla-m** [pnsn/mustangular#18]
Toggle an average across all channels.  Use existing channels.

**Comment by kyla-m** [comment]
Minimum, Maximum, Most Extreme

**Comment by gillian-earthscope** [comment]
This feature request has been changed from averaging across all channels to adding option to select which channel to display by min, max, most extreme (similar to mustangular v1). Possible way to make this intuitive to users:

1. Move the Value section above Channel Priority and rename as 'Channel Value Across Timespan"
2. Create section 'Channel Choice for Co-located Channels'
2. In this section, have radio option for Channel Priority box or Max/Min/Most Extreme dropdown.

**Comment by kyla-m** [comment]
To clarify, are users still supposed to be able to set channel priority when there are not co-located channels?

**Comment by gillian-earthscope** [comment]
Does the channel priority do anything now when there are not co-located channels? I don't think the functionality needs to change. 

To clarify, we're talking about the situation in this example where TA.A36M only has BHZ and N4.060A only has HHZ, with neither having co-located channels? 
http://ds.iris.edu/mustang/mustangular/#/map?net=TA,N4&cha=BHZ,HHZ&sta=A36M,060A&start=2021-04-01&end=2021-04-02&metric=PERCENT_AVAILABILITY&coloring=red_to_green&invert=false&bincount=5&binmin=0&binmax=100&value=Average&channels=BHZ,HHZ

**Comment by kyla-m** [comment]
The priority wouldn't do anything if there is only one station for the channel, since there is only one channel available. Thank you that makes sense.
