### ISSUE TITLE
MUSTANGular using PDT time zone instead of GMT/UTC

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#2]
The selected start and end date in the MUSTANGular query gets sent to MUSTANG as the local PDT time zone instead of GMT/UTC. This results in returned value that do not match the intended dates. 

For example, selecting a start date of 08/12/2018 and an end date of 08/14/2018 produces this MUSTANG query: 

http://service.iris.edu/mustang/measurements/1/query?nodata=200&net=IU&start=2018-08-12T07:00:00.000&end=2018-08-14T07:00:00.000&metric=PERCENT_AVAILABILITY&output=text 

This query will not return values for 08/12/2018 (for metrics that have start times of 00:00:00).

**Comment by kyla-m** [comment]
Thanks for pointing that out. I've fixed it and will update it on assets shortly.

**Comment by gillian-earthscope** [comment]
The fix does not work correctly. For example, I select start and end dates of 08/01/2018 - 08/16/2018 and it makes a MUSTANG request for 07/31/2018 - 08/15/2018. Then when I navigate back to the query page, it shows start and end dates of 07/30/2018 - 08/14/2018.

**Comment by kyla-m** [comment]
What internet browser are you using? I can't reproduce that behavior since the fix.

**Comment by gillian-earthscope** [comment]
I’m using Safari.

-Gillian

**Comment by kyla-m** [comment]
Thanks! I'll check it out.

**Comment by gillian-earthscope** [comment]
I just tried it on Firefox, and it works ok there. It looks like it’s only a Safari issue.

-Gillian

**Comment by kyla-m** [comment]
Yes, it appears to be caused by safari. They don't follow the same standard for dates as the other browsers. It is fixable though.

**Comment by kyla-m** [comment]
Fixed, works the same on safari, chrome, and firefox.

**Comment by gillian-earthscope** [comment]
This also affects the plotting in Safari; the data points for metrics that start at 00:00 appear to be offset to midday. Firefox plots dates accurately.

Safari example:
![safari](https://user-images.githubusercontent.com/22774506/49253897-9b614d00-f3dc-11e8-8264-ad7f950f6aca.png)

Firefox, same plot:
![firefox](https://user-images.githubusercontent.com/22774506/49253959-ccda1880-f3dc-11e8-8b81-f28ac66cf455.png)

**Comment by kyla-m** [comment]
Fixed by ensuring UTC use in safari.
