### ISSUE TITLE
Inconsistency found when binning, plus feedback on color scheme

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#3]
For a percent_availability query the default binning was min=0, max=100, and number of bins=5. This resulted in the majority of stations being colored grey (values =100 put into the  >= 100 bin). 
![bin1](https://user-images.githubusercontent.com/22774506/44174368-c4610a80-a097-11e8-83f0-6b35b2e6b92e.png)
Then when I specified the minimum bin to be 0.1, the previously grey circles are now green and in the 80-100 bin, instead of the >=100 bin, even though their values are still 100.
![bin2](https://user-images.githubusercontent.com/22774506/44174436-00946b00-a098-11e8-80f2-f35556a0bc0d.png)
When I changed the minimum bin to 0.01, the values=100 were put back into the grey >=100 bin.
![bin3](https://user-images.githubusercontent.com/22774506/44174451-0be79680-a098-11e8-8141-912e7248485f.png)
And on a more general note, using black and grey as the lower and upper colors in the scheme tends to be confusing. It's not intuitive which is high and which is low, and without looking at the key I think of these colors as close to each other and not on opposite ends of a spectrum.

**Comment by kyla-m** [comment]
This is due to the key only showing 2 decimal places even though the bins have more than that. The bins changed enough that the values correctly switched to a different bin. 

I changed the binning to only have 2 decimal places.
