### ISSUE TITLE
Start and end date selection issue when editing

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#31]
If you hit the 'Edit Query' button to take you back to the input form and then try to change the dates, you cannot select an end date prior to the original start date, even after you change the start date to an earlier date. As an example, my original query was:
http://ds.iris.edu/mustang/mustangular/#/map?net=TA&cha=BHZ&sta=A%3F%3F%3F&start=2020-04-19&end=2020-04-21&metric=NUM_GAPS

From the input form page, I changed the start date to 2020-04-12 and the valid end date selections were blacked out prior to 2020-04-19. See attached screenshot.
<img width="908" alt="enddate_issue" src="https://user-images.githubusercontent.com/22774506/80430997-1fa35280-88a5-11ea-8a45-d0b7381d27e1.png">

Conversely, I also can't choose a new start date after the original end date.

**Comment by kyla-m** [comment]
Fixed: changed calendar to use currently selected dates instead of initial dates.

**Comment by kyla-m** [comment]
Was this still an issue?
