### ISSUE TITLE
dead_channel_gsn metric binning error

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#4]
The dead_channel_gsn is a boolean metric with values of 0,1 and MUSTANGular is not handling this well. When I make a request that has mixed 0,1 values then nothing appears on the map or key. The max bin entry box shows 0, but the "max=" bin number above it is impossibly large. The number of bins is 0. If I have multiple metrics in the request, then switching to another metric also does not produce a key or map, although the bins look ok.
![gsn1](https://user-images.githubusercontent.com/22774506/44279240-7e29b980-a205-11e8-9396-dac3bdbefa23.png)

If I make a request for dead_channel_gsn that only returns values of 0 then it does produce a map, but the key values are <-0.01 and >=. The >= has no number listed and the number of bins is 0. 
![gsn2](https://user-images.githubusercontent.com/22774506/44279461-4cfdb900-a206-11e8-8a9f-1d75086222bf.png)

**Comment by kyla-m** [comment]
Fixed binning for small range of values.

**Comment by kyla-m** [comment]
Binning defaults for boolean values is still strange. Fix this.
