### ISSUE TITLE
PDF plots don't cover entire date range

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#5]
When clicking on the station PDF links, the PDF plots do not include the last day in the request.

For example, a search for TA network stations and BHZ channels for 09/01-09/07/2018 (http://ds.iris.edu/mustang/mustangular/#/map?net=TA&cha=BHZ&start=2018-09-01&end=2018-09-07&metric=SAMPLE_MEAN) results in a PDF query that does not include the last day (https://service.iris.edu/mustang/noise-pdf/1/query?target=TA.C36M.--.BHZ.M&starttime=2018-09-01&endtime=2018-09-06&format=plot, which covers data through 2018-09-05T23:59:59)

**Comment by kyla-m** [comment]
This was due to the link being generated with the date from the last data point, not the query. Fixed by making sure the request uses the date from the query.
