### ISSUE TITLE
metrics with <=2 values per station-channel for the timespan result in error when clicking on station

### ISSUE THREAD

**Issue by gillian-earthscope** [pnsn/mustangular#6]
There are a group of metrics that only return a single value for any time span (ts_gap_length_total, ts_max_gap_total, ts_num_gaps_total, ts_percent_availability_total). When I click on a station (click to view data), these result in an 'ERROR TypeError: "n is undefined" message' in the web console. This can also happen with event-based metrics such as polarity_check if only one or two events result in values for the time span. 

After this error happens, I cannot successfully click on stations for plots even if I change to an available metric that has daily values (which should be able produce a time series plot). I also have no access to the PDF plot links. I have to start over from the query form page to regain this functionality.

**Comment by kyla-m** [comment]
Can you send me a query that you used that produced this? Thanks!

**Comment by gillian-earthscope** [comment]
Here is one query:

http://ds.iris.edu/mustang/mustangular/#/map?net=TA&cha=BHZ&start=2018-12-02&end=2018-12-06&metric=TS_NUM_GAPS,TS_NUM_GAPS_TOTAL <http://ds.iris.edu/mustang/mustangular/#/map?net=TA&cha=BHZ&start=2018-12-02&end=2018-12-06&metric=TS_NUM_GAPS,TS_NUM_GAPS_TOTAL>

**Comment by kyla-m** [comment]
This was caused by a bug in the code, which has been fixed.
